# Generated by Django 4.0.6 on 2022-08-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_image_room_alter_room_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
